// convertThemes.ts 
import { writeFileSync } from 'fs';
import path from 'path';
import themes from 'daisyui/theme/object.js';

const PREFIX = '--color-';

// 可选：替换 key 的函数（目前未做 - 保留原样）
const convertKey = (key: string): string => {
    if (key.startsWith(PREFIX)) {
        return key.slice(PREFIX.length); // e.g. --color-primary → primary
    }
    return key;
};

// 允许保留的非 color 变量
const ALLOWED_KEYS = ['color-scheme'];

// 将 DaisyUI 原始主题格式，转换为扁平 key-value 格式
function convertThemeRawFormat(raw: Record<string, unknown>): Record<string, string> {
    const result: Record<string, string> = {};

    for (const [k, v] of Object.entries(raw)) {
        if (typeof v !== 'string') continue;

        if (k.startsWith(PREFIX)) {
            result[convertKey(k)] = v;
        } else if (ALLOWED_KEYS.includes(k)) {
            result[k] = v;
        }
    }

    return result;
}

// 过滤函数，根据字段数组返回新对象
function filterThemeFields(
    themeObj: Record<string, string>,
    fields: string[]
): Record<string, string> {
    if (fields.length === 1 && fields[0] === '') {
        // 特殊规则：[''] 表示保留全部字段
        return { ...themeObj };
    }

    const filtered: Record<string, string> = {};
    for (const key of fields) {
        if (key in themeObj) {
            filtered[key] = themeObj[key];
        }
    }
    return filtered;
}

// 构造转换后的主题对象
const convertedThemes: Record<string, Record<string, string>> = {};
for (const [themeName, themeObj] of Object.entries(themes)) {
    const plainTheme: Record<string, unknown> = { ...themeObj };
    convertedThemes[themeName] = convertThemeRawFormat(plainTheme);
}

// 字段配置
const min_field_array = ['color-scheme'];
const mid_field_array = [
    'color-scheme',
    'base-100',
    'base-200',
    'base-300',
    'base-content',
    'primary',
    'primary-content'
];
const max_field_array = [''];

// 输出目录
const outputDir = path.resolve(__dirname, '../styles/daisyui');
const output_MinPath = path.join(outputDir, 'theme_min.ts');
const output_MidPath = path.join(outputDir, 'theme_mid.ts');
const output_MaxPath = path.join(outputDir, 'theme_max.ts');

// 生成不同版本的字段对象
function generateFilteredThemes(
    fields: string[]
): Record<string, Record<string, string>> {
    const filteredThemes: Record<string, Record<string, string>> = {};
    for (const [themeName, themeData] of Object.entries(convertedThemes)) {
        filteredThemes[themeName] = filterThemeFields(themeData, fields);
    }
    return filteredThemes;
}

// 写入函数
function writeThemeFile(filepath: string, filetype: string, themesObj: Record<string, Record<string, string>>) {
    const content = `// This file is auto-generated by convertThemes.ts
// Do not edit manually

export const daisyui_themes_${filetype} = ${JSON.stringify(themesObj, null, 2)};
`;
    writeFileSync(filepath, content, { encoding: 'utf-8' });
}

// 执行写入
writeThemeFile(output_MinPath, "min", generateFilteredThemes(min_field_array));
writeThemeFile(output_MidPath, "mid", generateFilteredThemes(mid_field_array));
writeThemeFile(output_MaxPath, "max", generateFilteredThemes(max_field_array));

console.log('✅ DaisyUI themes written to:');
console.log('  ', output_MinPath);
console.log('  ', output_MidPath);
console.log('  ', output_MaxPath);
