// This file is auto-generated by convertThemes.ts
// Do not edit manually

export const daisyui_themes_mid = {
  forest: {
    "color-scheme": "dark",
    "base-100": "oklch(20.84% 0.008 17.911)",
    "base-200": "oklch(18.522% 0.007 17.911)",
    "base-300": "oklch(16.203% 0.007 17.911)",
    "base-content": "oklch(83.768% 0.001 17.911)",
    "primary": "oklch(68.628% 0.185 148.958)",
    "primary-content": "oklch(0% 0 0)"
  },
  cyberpunk: {
    "color-scheme": "light",
    "base-100": "oklch(94.51% 0.179 104.32)",
    "base-200": "oklch(91.51% 0.179 104.32)",
    "base-300": "oklch(85.51% 0.179 104.32)",
    "base-content": "oklch(0% 0 0)",
    "primary": "oklch(74.22% 0.209 6.35)",
    "primary-content": "oklch(14.844% 0.041 6.35)"
  },
  cupcake: {
    "color-scheme": "light",
    "base-100": "oklch(97.788% 0.004 56.375)",
    "base-200": "oklch(93.982% 0.007 61.449)",
    "base-300": "oklch(91.586% 0.006 53.44)",
    "base-content": "oklch(23.574% 0.066 313.189)",
    "primary": "oklch(85% 0.138 181.071)",
    "primary-content": "oklch(43% 0.078 188.216)"
  },
  fantasy: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(93% 0 0)",
    "base-300": "oklch(86% 0 0)",
    "base-content": "oklch(27.807% 0.029 256.847)",
    "primary": "oklch(37.45% 0.189 325.02)",
    "primary-content": "oklch(87.49% 0.037 325.02)"
  },
  wireframe: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(97% 0 0)",
    "base-300": "oklch(94% 0 0)",
    "base-content": "oklch(20% 0 0)",
    "primary": "oklch(87% 0 0)",
    "primary-content": "oklch(26% 0 0)"
  },
  cmyk: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(95% 0 0)",
    "base-300": "oklch(90% 0 0)",
    "base-content": "oklch(20% 0 0)",
    "primary": "oklch(71.772% 0.133 239.443)",
    "primary-content": "oklch(14.354% 0.026 239.443)"
  },
  emerald: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(93% 0 0)",
    "base-300": "oklch(86% 0 0)",
    "base-content": "oklch(35.519% 0.032 262.988)",
    "primary": "oklch(76.662% 0.135 153.45)",
    "primary-content": "oklch(33.387% 0.04 162.24)"
  },
  nord: {
    "color-scheme": "light",
    "base-100": "oklch(95.127% 0.007 260.731)",
    "base-200": "oklch(93.299% 0.01 261.788)",
    "base-300": "oklch(89.925% 0.016 262.749)",
    "base-content": "oklch(32.437% 0.022 264.182)",
    "primary": "oklch(59.435% 0.077 254.027)",
    "primary-content": "oklch(11.887% 0.015 254.027)"
  },
  halloween: {
    "color-scheme": "dark",
    "base-100": "oklch(21% 0.006 56.043)",
    "base-200": "oklch(14% 0.004 49.25)",
    "base-300": "oklch(0% 0 0)",
    "base-content": "oklch(84.955% 0 0)",
    "primary": "oklch(77.48% 0.204 60.62)",
    "primary-content": "oklch(19.693% 0.004 196.779)"
  },
  night: {
    "color-scheme": "dark",
    "base-100": "oklch(20.768% 0.039 265.754)",
    "base-200": "oklch(19.314% 0.037 265.754)",
    "base-300": "oklch(17.86% 0.034 265.754)",
    "base-content": "oklch(84.153% 0.007 265.754)",
    "primary": "oklch(75.351% 0.138 232.661)",
    "primary-content": "oklch(15.07% 0.027 232.661)"
  },
  silk: {
    "color-scheme": "light",
    "base-100": "oklch(97% 0.0035 67.78)",
    "base-200": "oklch(95% 0.0081 61.42)",
    "base-300": "oklch(90% 0.0081 61.42)",
    "base-content": "oklch(40% 0.0081 61.42)",
    "primary": "oklch(23.27% 0.0249 284.3)",
    "primary-content": "oklch(94.22% 0.2505 117.44)"
  },
  coffee: {
    "color-scheme": "dark",
    "base-100": "oklch(24% 0.023 329.708)",
    "base-200": "oklch(21% 0.021 329.708)",
    "base-300": "oklch(16% 0.019 329.708)",
    "base-content": "oklch(72.354% 0.092 79.129)",
    "primary": "oklch(71.996% 0.123 62.756)",
    "primary-content": "oklch(14.399% 0.024 62.756)"
  },
  winter: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(97.466% 0.011 259.822)",
    "base-300": "oklch(93.268% 0.016 262.751)",
    "base-content": "oklch(41.886% 0.053 255.824)",
    "primary": "oklch(56.86% 0.255 257.57)",
    "primary-content": "oklch(91.372% 0.051 257.57)"
  },
  light: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(98% 0 0)",
    "base-300": "oklch(95% 0 0)",
    "base-content": "oklch(21% 0.006 285.885)",
    "primary": "oklch(45% 0.24 277.023)",
    "primary-content": "oklch(93% 0.034 272.788)"
  },
  valentine: {
    "color-scheme": "light",
    "base-100": "oklch(97% 0.014 343.198)",
    "base-200": "oklch(94% 0.028 342.258)",
    "base-300": "oklch(89% 0.061 343.231)",
    "base-content": "oklch(52% 0.223 3.958)",
    "primary": "oklch(65% 0.241 354.308)",
    "primary-content": "oklch(100% 0 0)"
  },
  lemonade: {
    "color-scheme": "light",
    "base-100": "oklch(98.71% 0.02 123.72)",
    "base-200": "oklch(91.8% 0.018 123.72)",
    "base-300": "oklch(84.89% 0.017 123.72)",
    "base-content": "oklch(19.742% 0.004 123.72)",
    "primary": "oklch(58.92% 0.199 134.6)",
    "primary-content": "oklch(11.784% 0.039 134.6)"
  },
  retro: {
    "color-scheme": "light",
    "base-100": "oklch(91.637% 0.034 90.515)",
    "base-200": "oklch(88.272% 0.049 91.774)",
    "base-300": "oklch(84.133% 0.065 90.856)",
    "base-content": "oklch(41% 0.112 45.904)",
    "primary": "oklch(80% 0.114 19.571)",
    "primary-content": "oklch(39% 0.141 25.723)"
  },
  aqua: {
    "color-scheme": "dark",
    "base-100": "oklch(37% 0.146 265.522)",
    "base-200": "oklch(28% 0.091 267.935)",
    "base-300": "oklch(22% 0.091 267.935)",
    "base-content": "oklch(90% 0.058 230.902)",
    "primary": "oklch(85.661% 0.144 198.645)",
    "primary-content": "oklch(40.124% 0.068 197.603)"
  },
  dark: {
    "color-scheme": "dark",
    "base-100": "oklch(25.33% 0.016 252.42)",
    "base-200": "oklch(23.26% 0.014 253.1)",
    "base-300": "oklch(21.15% 0.012 254.09)",
    "base-content": "oklch(97.807% 0.029 256.847)",
    "primary": "oklch(58% 0.233 277.117)",
    "primary-content": "oklch(96% 0.018 272.314)"
  },
  lofi: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(97% 0 0)",
    "base-300": "oklch(94% 0 0)",
    "base-content": "oklch(0% 0 0)",
    "primary": "oklch(15.906% 0 0)",
    "primary-content": "oklch(100% 0 0)"
  },
  dim: {
    "color-scheme": "dark",
    "base-100": "oklch(30.857% 0.023 264.149)",
    "base-200": "oklch(28.036% 0.019 264.182)",
    "base-300": "oklch(26.346% 0.018 262.177)",
    "base-content": "oklch(82.901% 0.031 222.959)",
    "primary": "oklch(86.133% 0.141 139.549)",
    "primary-content": "oklch(17.226% 0.028 139.549)"
  },
  dracula: {
    "color-scheme": "dark",
    "base-100": "oklch(28.822% 0.022 277.508)",
    "base-200": "oklch(26.805% 0.02 277.508)",
    "base-300": "oklch(24.787% 0.019 277.508)",
    "base-content": "oklch(97.747% 0.007 106.545)",
    "primary": "oklch(75.461% 0.183 346.812)",
    "primary-content": "oklch(15.092% 0.036 346.812)"
  },
  corporate: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(93% 0 0)",
    "base-300": "oklch(86% 0 0)",
    "base-content": "oklch(22.389% 0.031 278.072)",
    "primary": "oklch(58% 0.158 241.966)",
    "primary-content": "oklch(100% 0 0)"
  },
  bumblebee: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(97% 0 0)",
    "base-300": "oklch(92% 0 0)",
    "base-content": "oklch(20% 0 0)",
    "primary": "oklch(85% 0.199 91.936)",
    "primary-content": "oklch(42% 0.095 57.708)"
  },
  business: {
    "color-scheme": "dark",
    "base-100": "oklch(24.353% 0 0)",
    "base-200": "oklch(22.648% 0 0)",
    "base-300": "oklch(20.944% 0 0)",
    "base-content": "oklch(84.87% 0 0)",
    "primary": "oklch(41.703% 0.099 251.473)",
    "primary-content": "oklch(88.34% 0.019 251.473)"
  },
  black: {
    "color-scheme": "dark",
    "base-100": "oklch(0% 0 0)",
    "base-200": "oklch(19% 0 0)",
    "base-300": "oklch(22% 0 0)",
    "base-content": "oklch(87.609% 0 0)",
    "primary": "oklch(35% 0 0)",
    "primary-content": "oklch(100% 0 0)"
  },
  acid: {
    "color-scheme": "light",
    "base-100": "oklch(98% 0 0)",
    "base-200": "oklch(95% 0 0)",
    "base-300": "oklch(91% 0 0)",
    "base-content": "oklch(0% 0 0)",
    "primary": "oklch(71.9% 0.357 330.759)",
    "primary-content": "oklch(14.38% 0.071 330.759)"
  },
  luxury: {
    "color-scheme": "dark",
    "base-100": "oklch(14.076% 0.004 285.822)",
    "base-200": "oklch(20.219% 0.004 308.229)",
    "base-300": "oklch(23.219% 0.004 308.229)",
    "base-content": "oklch(75.687% 0.123 76.89)",
    "primary": "oklch(100% 0 0)",
    "primary-content": "oklch(20% 0 0)"
  },
  sunset: {
    "color-scheme": "dark",
    "base-100": "oklch(22% 0.019 237.69)",
    "base-200": "oklch(20% 0.019 237.69)",
    "base-300": "oklch(18% 0.019 237.69)",
    "base-content": "oklch(77.383% 0.043 245.096)",
    "primary": "oklch(74.703% 0.158 39.947)",
    "primary-content": "oklch(14.94% 0.031 39.947)"
  },
  garden: {
    "color-scheme": "light",
    "base-100": "oklch(92.951% 0.002 17.197)",
    "base-200": "oklch(86.445% 0.002 17.197)",
    "base-300": "oklch(79.938% 0.001 17.197)",
    "base-content": "oklch(16.961% 0.001 17.32)",
    "primary": "oklch(62.45% 0.278 3.836)",
    "primary-content": "oklch(100% 0 0)"
  },
  autumn: {
    "color-scheme": "light",
    "base-100": "oklch(95.814% 0 0)",
    "base-200": "oklch(89.107% 0 0)",
    "base-300": "oklch(82.4% 0 0)",
    "base-content": "oklch(19.162% 0 0)",
    "primary": "oklch(40.723% 0.161 17.53)",
    "primary-content": "oklch(88.144% 0.032 17.53)"
  },
  caramellatte: {
    "color-scheme": "light",
    "base-100": "oklch(98% 0.016 73.684)",
    "base-200": "oklch(95% 0.038 75.164)",
    "base-300": "oklch(90% 0.076 70.697)",
    "base-content": "oklch(40% 0.123 38.172)",
    "primary": "oklch(0% 0 0)",
    "primary-content": "oklch(100% 0 0)"
  },
  pastel: {
    "color-scheme": "light",
    "base-100": "oklch(100% 0 0)",
    "base-200": "oklch(98.462% 0.001 247.838)",
    "base-300": "oklch(92.462% 0.001 247.838)",
    "base-content": "oklch(20% 0 0)",
    "primary": "oklch(90% 0.063 306.703)",
    "primary-content": "oklch(49% 0.265 301.924)"
  },
  synthwave: {
    "color-scheme": "dark",
    "base-100": "oklch(15% 0.09 281.288)",
    "base-200": "oklch(20% 0.09 281.288)",
    "base-300": "oklch(25% 0.09 281.288)",
    "base-content": "oklch(78% 0.115 274.713)",
    "primary": "oklch(71% 0.202 349.761)",
    "primary-content": "oklch(28% 0.109 3.907)"
  },
  abyss: {
    "color-scheme": "dark",
    "base-100": "oklch(20% 0.08 209)",
    "base-200": "oklch(15% 0.08 209)",
    "base-300": "oklch(10% 0.08 209)",
    "base-content": "oklch(90% 0.076 70.697)",
    "primary": "oklch(92% 0.2653 125)",
    "primary-content": "oklch(50% 0.2653 125)"
  }
};
