// This file is auto-generated by convertThemes.ts
// Do not edit manually

export const daisyui_themes_min = {
  forest: {
    "color-scheme": "dark"
  },
  cyberpunk: {
    "color-scheme": "light"
  },
  cupcake: {
    "color-scheme": "light"
  },
  fantasy: {
    "color-scheme": "light"
  },
  wireframe: {
    "color-scheme": "light"
  },
  cmyk: {
    "color-scheme": "light"
  },
  emerald: {
    "color-scheme": "light"
  },
  nord: {
    "color-scheme": "light"
  },
  halloween: {
    "color-scheme": "dark"
  },
  night: {
    "color-scheme": "dark"
  },
  silk: {
    "color-scheme": "light"
  },
  coffee: {
    "color-scheme": "dark"
  },
  winter: {
    "color-scheme": "light"
  },
  light: {
    "color-scheme": "light"
  },
  valentine: {
    "color-scheme": "light"
  },
  lemonade: {
    "color-scheme": "light"
  },
  retro: {
    "color-scheme": "light"
  },
  aqua: {
    "color-scheme": "dark"
  },
  dark: {
    "color-scheme": "dark"
  },
  lofi: {
    "color-scheme": "light"
  },
  dim: {
    "color-scheme": "dark"
  },
  dracula: {
    "color-scheme": "dark"
  },
  corporate: {
    "color-scheme": "light"
  },
  bumblebee: {
    "color-scheme": "light"
  },
  business: {
    "color-scheme": "dark"
  },
  black: {
    "color-scheme": "dark"
  },
  acid: {
    "color-scheme": "light"
  },
  luxury: {
    "color-scheme": "dark"
  },
  sunset: {
    "color-scheme": "dark"
  },
  garden: {
    "color-scheme": "light"
  },
  autumn: {
    "color-scheme": "light"
  },
  caramellatte: {
    "color-scheme": "light"
  },
  pastel: {
    "color-scheme": "light"
  },
  synthwave: {
    "color-scheme": "dark"
  },
  abyss: {
    "color-scheme": "dark"
  }
};
