

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

/* import { useEffect } from 'react'; */
/* import { useState, useLayoutEffect, useEffect } from 'react'; */
/* import { useState, useLayoutEffect, useEffect } from 'react'; */
import "@/css/base.css";   //20250630，添加此行。实测：无效果改变
import "@/app/globals.css";
// import "@radix-ui/themes/styles.css";
// import "@/app/css/index.css";
// import "@/css/tailwind-safelist.css";
// import "@/utils/styles/tailwind/safelist"; // ⬅️ 保留你自定义的 safelist

// import { Theme } from "@radix-ui/themes";
import Script from "next/script";
import Header from "@/components/Header/Page";

import { ReduxProvider } from '@/app/providers';
// import PrintInfo from "@/components/PrintInfo/Page";
// import { Provider } from 'react-redux';
// import rtkStore from '@/reduxToolKit/index';
import { Toaster } from 'sonner';
import { theme_const } from "@/config/theme_language_constants";
/* import { ab_ui } from '@/config/ui' */

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */
/* ----const getThemeName = async () => {
  try {
    const themeName:string = await new Promise((resolve, reject) => {
      try {
        resolve(localStorage.getItem("themeName") ?? ab_ui.default_theme);
      } catch (error) {
        reject(error);
      }
    });
    return themeName;
  } catch (error) {
    console.error("Error retrieving theme name:", error);
    return "";
  }
}; ----*/

/*---- export default async function RootLayout({ ----*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en"
      /* className={localStorage.getItem("darkMode") === "true" ? "dark":"light"} */
      /* data-theme={localStorage.getItem("darkMode") === "true" ? "dark" : "light"} */

      // data-theme={theme_const.default_theme_name}
      // color-scheme={theme_const.default_color_scheme}
      // data-theme=""
      // color-scheme=""
    >
      <head>
        <Script id="set-theme-before-paint" strategy="beforeInteractive">
          {`
            try {
              const themeKey = '${theme_const.theme_key}';
              const defaultTheme = '${theme_const.default_theme_name}';
              const savedTheme = localStorage.getItem(themeKey) || defaultTheme;
              document.documentElement.setAttribute('data-theme', savedTheme);
              document.documentElement.setAttribute('color-scheme', savedTheme === 'dark' ? 'dark' : 'light');
            } catch(e) {
              console.error('set-theme-before-paint error', e);
            }
          `}
        </Script>

        {/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-YGKELFKMTM"></script>
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-YGKELFKMTM');
            `} */}
        {/* 1️⃣ GA 脚本加载 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-YGKELFKMTM"
          strategy="afterInteractive"
        />
        {/* 2️⃣ GA 初始化配置 */}
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-YGKELFKMTM');
          `}
        </Script>
      </head>
      <body

      /* className="bg-white dark:bg-slate-900 dark:text-white" */
      >
        {/* <Theme> */}
        <ReduxProvider>
          {/* <Header thmemstr={tName} /> */}
          <Header />
          {/* <Header/> */}
          {children}
          {/* 
            Toaster 不需要包裹 {children}，放在{children}后是对的！
            原因：
              <Toaster /> 是一个独立挂载的 UI 组件，它会自动将所有 toast() 渲染为浮层提示
              （Portal 式），不影响页面本身结构。它不需要上下文传递，也不会干涉子组件。
             */}
          <Toaster
            // unstyled={true} // Toaster不支持此属性。 正确位置！此处才生效！
            position="top-center"
            /* 
            richColors 功能说明：
            启用后，会自动为不同类型的 toast（success, error, warning, info, default）：
             */
            // richColors
            /* 
            closeButton 是关闭按钮
             */
            // closeButton
            // unstyled={true} // ✅ 关闭默认样式，启用你自己定义的样式体系
            /* 如果不设置：expand，旧的提示拦会被缩小，并且新的提示会覆盖旧的 */
            expand // 防止 toast 被覆盖：禁止旧 toast 被缩放！每条 toast 都占据独立高度！
            className="!space-y-16" // 每条 toast 间距足够，不遮挡。
            // className="!space-y-1 transition-all duration-200"
            toastOptions={{
              // unstyled: true, // ❗ 如果使用 sonner 的话，这个可能要加
              unstyled: true, // 关闭默认样式
              // toastOptions.className 应用于「每个 toast 项」本身
              duration: 4000, // 让它有个消失时间，才能触发 fade
              // className: 'fade-toast !top-[100px]', // 控制单个 toast 的位置偏移--你可以改为 80px、120px 等              
              // className: 'fade-toast !top-[100px] rounded-lg border border-white/20 bg-white/10 backdrop-blur',
              // className: 'fade-toast toast-glass !top-[100px]', // 🎯 样式关键
              // className: 'fade-toast toast-glass !top-[100px]', // 🎯 样式关键
              className: '!top-[100px]', // 不要挡住搜索拦的位置偏移
              style: {
                boxShadow: 'none',         // 干净清爽。去除 toast 的浮层阴影，避免上下 toast 阴影互相遮挡
                margin: 0,                 // 清除默认外边距，防止出现 toast 压重影
              },
            }}
            // ⬇️ 额外配置：延迟卸载 toast（否则动画来不及播完就被移除）
            // duration={3000}
            // exitDuration={1000} // Toaster不支持此属性。 给动画足够退场时间
            /* 
            visibleToasts 是一个“最大并发显示 toast 数”的限制器，和动画卸载（如 exitDuration）无关，也不是必需的。
            默认值是 Infinity，也就是不限制显示数量。
             */
            visibleToasts={Infinity}
          // expand
          // closeButton
          /**
           * ⬇️ 添加这个关键参数（0.7s 退场动画 + 安全边界）
           */

          />{/* 全局提示组件 */}
        </ReduxProvider>
        {/* </Theme> */}
      </body>
    </html>


  );
}
